# Generated by Django 6.0.2 on 2026-03-07 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('app_secret', models.CharField(max_length=255)),
                ('webhook_verify_token', models.CharField(max_length=255)),
                ('config', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waba_id', models.CharField(max_length=255)),
                ('phone_number_id', models.CharField(max_length=255)),
                ('display_phone_number', models.CharField(max_length=50)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quality_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('messaging_limit_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to='business.business')),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number_id'], name='integration_phone_n_46e1b8_idx'), models.Index(fields=['business'], name='integration_busines_e7b5fa_idx')],
            },
        ),
    ]
