# Generated by Django 6.0.2 on 2026-03-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_titile_app',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
