# Generated by Django 6.0.2 on 2026-03-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_app_app_titile_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_titile_app',
            new_name='app_title',
        ),
    ]
