# Generated by Django 6.0.2 on 2026-03-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_rename_app_titile_app_app_app_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_title',
            field=models.CharField(blank=True, choices=[('WHATSAPP_CLOUD', 'Whatsapp Cloud'), ('MESSANGER', 'Messanger')], max_length=255, null=True),
        ),
    ]
