# Generated by Django 6.0.2 on 2026-03-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_alter_app_app_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='meta_business_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
