# Generated by Django 6.0.2 on 2026-03-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_whatsappaccount_meta_business_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='whatsappaccount',
            name='token_expiry',
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='access_token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
