# Generated by Django 6.0.2 on 2026-03-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
