# Generated by Django 6.0.2 on 2026-03-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('OPENAPI', 'Openapi'), ('GEMINI', 'Gemini')], default='OPENAPI', max_length=20)),
                ('instructions_rules', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
