# Generated by Django 6.0.2 on 2026-03-09 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessmember_delete_teaminvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmember',
            name='email',
        ),
        migrations.AddField(
            model_name='businessmember',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='live_chat_notification_sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='role',
            field=models.CharField(default=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('AGENT', 'Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
