# Generated by Django 6.0.2 on 2026-03-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_businessmember_email_businessmember_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('AGENT', 'Agent')], default='ADMIN', max_length=50),
        ),
    ]
