# Generated by Django 6.0.2 on 2026-03-17 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businessmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInformationForAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('business_details', models.TextField(blank=True, null=True)),
                ('product_details', models.TextField(blank=True, null=True)),
                ('service_details', models.TextField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_information_for_ai', to='business.business')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
