# Generated by Django 6.0.2 on 2026-03-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_businessinformationforai'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformationforai',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
