# Generated by Django 6.0.2 on 2026-03-07 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('expired', 'Expired'), ('transferred', 'Transferred')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('instagram', 'Instagram')], default='whatsapp', max_length=20)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='business.business')),
                ('whatsapp_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='integration.whatsappaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='business.business')),
                ('whatsapp_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='integration.whatsappaccount')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='lead.lead'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=20)),
                ('message_type', models.CharField(choices=[('Text', 'Text'), ('Image', 'Image'), ('Audio', 'Audio'), ('Video', 'Video'), ('File', 'File')], default='Text', max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='messages/')),
                ('meta_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Failed', 'Failed')], default='Sent', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='business.business')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.conversation')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lead.lead')),
                ('whatsapp_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='integration.whatsappaccount')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='media/')),
                ('meta_media_id', models.CharField(max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.conversation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_number'], name='lead_lead_phone_n_eb14eb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business', 'phone_number'], name='lead_lead_busines_48f0f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('business', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business'], name='lead_conver_busines_0fb3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='lead_conver_last_me_01e908_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['meta_message_id'], name='lead_messag_meta_me_87d2bb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='lead_messag_convers_3c3303_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['business', 'timestamp'], name='lead_messag_busines_142902_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['lead'], name='lead_messag_lead_id_ed91d6_idx'),
        ),
    ]
