# Generated by Django 6.0.2 on 2026-03-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_message_options_alter_mediafile_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Received', 'Received'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Failed', 'Failed')], default='Sent', max_length=50),
        ),
    ]
