# Generated by Django 6.0.2 on 2026-03-14 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businessmember_role'),
        ('integration', '0006_remove_whatsappaccount_refresh_token_and_more'),
        ('lead', '0005_alter_message_business_alter_message_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='business',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='business.business'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='lead',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='lead.lead'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='whatsapp_account',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='integration.whatsappaccount'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='business',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='business.business'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='whatsapp_account',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='integration.whatsappaccount'),
        ),
    ]
