# Generated by Django 6.0.2 on 2026-03-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
