# Generated by Django 6.0.2 on 2026-03-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businessmember_role'),
        ('integration', '0006_remove_whatsappaccount_refresh_token_and_more'),
        ('lead', '0009_message_system_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='lead_messag_meta_me_87d2bb_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['system_id'], name='lead_messag_system__372c6c_idx'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='meta_message_id',
        ),
    ]
