# Generated by Django 6.0.2 on 2026-03-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_remove_message_lead_messag_meta_me_87d2bb_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
    ]
