# Generated by Django 6.0.2 on 2026-03-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_by',
            field=models.CharField(choices=[('AI', 'Ai'), ('AGENT', 'Agent')], default='AI', max_length=50),
        ),
    ]
