# Generated by Django 6.0.2 on 2026-03-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_alter_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_by',
            field=models.CharField(choices=[('AI', 'Ai'), ('AGENT', 'Agent'), ('CLIENT', 'Client')], default='AI', max_length=50),
        ),
    ]
