# Generated by Django 6.0.2 on 2026-03-09 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessmember_delete_teaminvite'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditLog',
            new_name='ActivityLog',
        ),
    ]
