# Generated by Django 6.0.2 on 2026-03-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_rename_auditlog_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='need_notify',
            field=models.BooleanField(default=False),
        ),
    ]
