# Generated by Django 6.0.2 on 2026-03-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_activitylog_need_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Login', 'Login'), ('Logout', 'Logout'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected')], max_length=50),
        ),
    ]
