# Generated by Django 6.0.2 on 2026-03-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='action',
            field=models.CharField(blank=True, choices=[('MESSAGE', 'Message'), ('STATUS', 'Status')], default='MESSAGE', max_length=30, null=True),
        ),
    ]
